import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '@components/navbar'
import Login from '@components/login'
import { AuthType } from '@components/navbar/navbar'


const Home: NextPage = () => {
  const auth:AuthType =  {
    data: {
      name: '',
      avatar: ''
    },
    isLoading: false,
    error: undefined
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar auth={auth}/>
        <Login />
      </main>
    </div>
  )
}

export default Home
