import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '@components/navbar'
import Login from '@components/login'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Login />
      </main>
    </div>
  )
}

export default Home
